<a href="https://colab.research.google.com/github/jtamas0705/learnpytorch/blob/main/pytorch_00_fundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

# Random tansors


In [ ]:
random_tensor = torch.rand(21 ,5 , 19, 39, 42)
random_tensor

tensor([[[[[1.1386e-01, 8.1235e-01, 8.7378e-02,  ..., 8.6606e-01,
            3.1394e-01, 2.2827e-01],
           [2.0690e-01, 5.1236e-01, 1.0703e-01,  ..., 5.2913e-01,
            4.9771e-01, 6.9243e-01],
           [8.0070e-01, 3.8526e-01, 8.2328e-01,  ..., 6.4743e-01,
            1.1713e-01, 9.6975e-01],
           ...,
           [9.7323e-02, 1.0654e-01, 9.6962e-02,  ..., 1.3275e-01,
            9.7424e-02, 3.8607e-01],
           [7.9689e-02, 5.2705e-01, 5.3565e-01,  ..., 1.8379e-01,
            9.5163e-01, 1.9132e-01],
           [6.6078e-01, 6.7079e-01, 1.0256e-01,  ..., 1.6428e-01,
            6.0930e-01, 8.7705e-02]],

          [[1.0291e-01, 9.2506e-01, 7.6415e-01,  ..., 7.9535e-01,
            2.5760e-01, 4.7533e-01],
           [7.5707e-02, 1.6113e-01, 5.3787e-02,  ..., 6.2281e-02,
            2.0999e-01, 6.5745e-01],
           [5.1378e-01, 9.3822e-01, 3.5484e-01,  ..., 5.0524e-01,
            5.8962e-01, 1.3495e-01],
           ...,
           [9.2983e-01, 6.6475e-01, 6.6

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])